language: csharp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    packages:
install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-2.0.0 -y
script: 
  - echo "========== build all .Net Core samples ============"
  - dotnet restore "UA Core Library.sln"
  - dotnet restore "UA-NetStandard.sln"
  - dotnet build -c Debug SampleApplications/Samples/NetCoreConsoleClient
  - dotnet build -c Debug SampleApplications/Samples/NetCoreConsoleServer
  - dotnet build -c Release SampleApplications/Samples/NetCoreConsoleClient
  - dotnet build -c Release SampleApplications/Samples/NetCoreConsoleServer
  - dotnet restore "SampleApplications/Workshop/Aggregation/UA Aggregation.sln"
  - dotnet build -c Debug SampleApplications/Workshop/Aggregation/ConsoleAggregationServer
  - dotnet build -c Release SampleApplications/Workshop/Aggregation/ConsoleAggregationServer
  - dotnet restore "SampleApplications/Workshop/Reference/UA Reference.sln"
  - dotnet build -c Debug SampleApplications/Workshop/Reference/ConsoleReferenceServer
  - dotnet build -c Release SampleApplications/Workshop/Reference/ConsoleReferenceServer

after_script:
  - echo "========== build done ============"


